name: Deploy Medallion

on:
  push:
    branches: [dev, test, main]

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.ref_name }} # dev, test, or main -> maps to prod below
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Map branch to env folder
        id: envmap
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then echo "env=prod" >> $GITHUB_OUTPUT
          else echo "env=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        working-directory: envs/${{ steps.envmap.outputs.env }}
        run: terraform init

      - name: Terraform Apply
        working-directory: envs/${{ steps.envmap.outputs.env }}
        run: terraform apply -auto-approve
        env:
          ARM_USE_OIDC: "true"
          TF_VAR_sql_admin_login: ${{ vars.SQL_ADMIN_LOGIN }}
          TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
